from re import template
from django.urls import path, include
from . import views
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='home'),
    path('indexAdmin/', views.indexAdmin, name='homeAdmin'),
    path('indexHV/', views.indexHV, name='homeHV'),
    path('indexGV/', views.indexGV, name='homeGV'),
    path('loginAdmin/',auth_views.LoginView.as_view(template_name="home/admin/loginAdmin.html"), name="loginAdmin"),
    path('login/', views.login, name='login'),
    path('loginGV/', views.loginGV, name='loginGV'),
    path('logout/', views.logout, name='logout'),
    path('logoutGV/', views.logoutGV, name='logoutGV'),
    path('account/', views.account, name='account'),
    path('dsHocVien/', views.dsHocVien, name='dsHocVien'),
    path('dsHocVienAdmin/', views.dsHocVienAdmin, name='dsHocVienAdmin'),
    path('dsLopHoc/', views.dsLopHoc, name='dsLopHoc'),
    path('dsLopHocHV/', views.dsLopHocHV, name='dsLopHocHV'),
    path('dsHocVienLop/<str:maLop>/', views.dsHocVienLop, name='dsHocVienLop'),
    path('accountGV/', views.accountGV, name='accountGV'),
    path('dsKhoaHoc/', views.dsKhoaHoc, name='dsKhoaHoc'),
    path('dangKyHoc',views.dangKyHoc, name='dangKyHoc'),
    path('send_email/',views.send_email, name='send_email'),
    path('hienThiThongTinPhuHuynh/<str:hocVien_id>/',views.hienThiThongTinPhuHuynh, name='hienThiThongTinPhuHuynh'),
    path('hienThiThongTinPhuHuynhAdmin/<str:hocVien_id>/',views.hienThiThongTinPhuHuynhAdmin, name='hienThiThongTinPhuHuynhAdmin'),
    path('diemDanh/', views.diemDanh, name='diemDanh'),
    path('export_excel/', views.export_excel, name='export_excel'),
    path('dsGiaoVien/', views.dsGiaoVien, name='dsGiaoVien'),
    path('dsGiaoVienAdmin/', views.dsGiaoVienAdmin, name='dsGiaoVienAdmin'),
    path('dsLopHocAdmin/', views.dsLopHocAdmin, name='dsLopHocAdmin'),
    path('addLopHoc/', views.addLopHoc, name='addLopHoc'),
    path(r"logout/$", auth_views.LogoutView.as_view(template_name="home/index.html"), name="logoutAdmin"),
    path('addHocVien/', views.addHocVien, name='addHocVien'),
    path('addGiaoVien/', views.addGiaoVien, name='addGiaoVien'),
    path('lichHoc/', views.lichHoc, name='lichHoc'),
    path('thongKe/', views.thongKe, name='thongKe'),
    path('import_excel/', views.import_excel, name='import_excel'),
    path('lichDay/', views.lichDay, name='lichDay'),
    path('dsKhoaHoc/', views.dsKhoaHoc, name='dsKhoaHoc'),
    path('deleteHocVien/', views.deleteHocVien, name='deleteHocVien'),
    path('deleteGiaoVien/', views.deleteGiaoVien, name='deleteGiaoVien'),
    path('deleteLopHoc/', views.deleteLopHoc, name='deleteLopHoc'),
    path('editHocVien/<str:maHV>/', views.editHocVien, name='editHocVien'),
    path('editGiaoVien/<str:maGV>/', views.editGiaoVien, name='editGiaoVien'),
    path('editLopHoc/<str:maLop>/', views.editLopHoc, name='editLopHoc'),
    path('addAdmin/', views.addAdmin, name='addAdmin'),
    path('dsAdmin/', views.dsAdmin, name='dsAdmin'),
    path('deleteAdmin/', views.deleteAdmin, name='deleteAdmin'),
    path('lopHocGV/<str:maGV>/', views.lopHocGV, name='lopHocGV'),
    path('hocVienLopAdmin/<str:maLop>/', views.hocVienLopAdmin, name='hocVienLopAdmin'),
    path('deleteKhoaHoc/', views.deleteKhoaHoc, name='deleteKhoaHoc'),
    path('editKhoaHoc/<str:maKH>/', views.editKhoaHoc, name='editKhoaHoc'),
    path('addKhoaHoc/', views.addKhoaHoc, name='addKhoaHoc'),
    path('addPhuHuynh/<str:maHV>/', views.addPhuHuynh, name='addPhuHuynh'),
    path('editHV/', views.editHV, name='editHV'),
    path('editGV/', views.editGV, name='editGV'),
    path('searchHV/', views.searchHV, name='searchHV'),
    path('searchGV/', views.searchGV, name='searchGV'),
    path('DDHVtheoNgay/', views.DDHVtheoNgay, name='DDHVtheoNgay'),
    path('addHVLH/<str:lopHoc_id>/', views.addHVLH, name='addHVLH'),
    path('xemLichHocAdmin/', views.xemLichHocAdmin, name='xemLichHocAdmin'),
    path('thongKeLopHoc/', views.thongKeLopHoc, name='thongKeLopHoc'),
    path('searchThongKe/', views.searchThongKe, name='searchThongKe'),
    path('locHV/', views.locHV, name='locHV'),
    path('dongTien/', views.dongTien, name='dongTien'),
    path('thongTinHocPhi/', views.thongTinHocPhi, name='thongTinHocPhi'),
    path('thanhToanLuong/', views.thanhToanLuong, name='thanhToanLuong'),
    path('tklh/', views.tklh, name='tklh'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
