# Generated by Django 4.0.5 on 2022-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_lophoc_soluonghocvien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocvien',
            name='password',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
