# Generated by Django 4.0.5 on 2022-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_hocvien_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaovien',
            name='password',
            field=models.CharField(default='1', max_length=50, null=True),
        ),
    ]
