# Generated by Django 4.0.5 on 2022-06-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_giaovien_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocvien_buoihoc',
            name='vangMat',
            field=models.BooleanField(null=True),
        ),
    ]
