# Generated by Django 4.0.5 on 2022-06-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_hocvien_buoihoc_vangmat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hocvien_buoihoc',
            name='dongTien',
        ),
        migrations.RemoveField(
            model_name='hocvien_buoihoc',
            name='vangMat',
        ),
    ]
