# Generated by Django 4.0.5 on 2022-06-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_hocvien_buoihoc_dongtien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocvien_buoihoc',
            name='diemDanhHV',
            field=models.BooleanField(default=False),
        ),
    ]
