# Generated by Django 4.0.5 on 2022-06-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_hocvien_buoihoc_diemdanhhv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='hocPhi_ca',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hocPhi_dot',
            field=models.IntegerField(default=0),
        ),
    ]
