# Generated by Django 4.0.5 on 2022-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_lophoc_hocphi_ca_alter_lophoc_hocphi_dot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocvien_buoihoc',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
