# Generated by Django 4.0.5 on 2022-06-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_hocvien_buoihoc_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocvien_buoihoc',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
