# Generated by Django 4.0.5 on 2022-06-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_hocvien_buoihoc_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocvien_lophoc',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
