# Generated by Django 4.0.5 on 2022-07-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_ngay_hocphi_hocvien_ngaydangky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hocphi_hocvien',
            name='hocPhi',
        ),
    ]
