# Generated by Django 4.0.5 on 2022-07-04 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_hocphi_hocvien_hocphi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocphi_hocvien',
            name='lopHoc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.lophoc'),
        ),
    ]
