# Generated by Django 4.0.5 on 2022-07-06 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_giaovien_buoihoc_cahoc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocvien',
            name='create_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 6, 21, 30, 25, 500493), null=True),
        ),
    ]
