# Generated by Django 4.0.5 on 2022-07-06 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_hocvien_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaovien',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 6, 21, 42, 54, 749633), null=True),
        ),
        migrations.AddField(
            model_name='khoahoc',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 6, 21, 42, 54, 753622), null=True),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='create_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 6, 21, 42, 54, 750630), null=True),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='create_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 6, 21, 42, 54, 749633), null=True),
        ),
    ]
