# Generated by Django 4.0.5 on 2022-07-06 17:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_giaovien_create_at_khoahoc_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaovien',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 7, 0, 47, 3, 622498), null=True),
        ),
        migrations.AlterField(
            model_name='hocvien',
            name='create_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 7, 0, 47, 3, 621501), null=True),
        ),
        migrations.AlterField(
            model_name='hocvien_lophoc',
            name='hocVien_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.hocvien'),
        ),
        migrations.AlterField(
            model_name='hocvien_lophoc',
            name='lopHoc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.lophoc'),
        ),
        migrations.AlterField(
            model_name='khoahoc',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 7, 0, 47, 3, 626489), null=True),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='create_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 7, 0, 47, 3, 622498), null=True),
        ),
        migrations.AlterField(
            model_name='phuhuynh',
            name='hocVien_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.hocvien'),
        ),
    ]
